kind: pipeline
name: default

steps:
  
- name: Deploy
  image: alpine
  environment:
    TF_VAR_auth_token: TF_VAR_auth_token
    TF_VAR_packet_project_id: TF_VAR_packet_project_id
  commands:
  - apk update
  - apk add openssh-client
  - apk add curl
  - apk add terraform
  - ssh-keygen -f id_rsa -P ""
  - ln -s terraform.tfvars.drone terraform.tfvars 
  - terraform init 
  - terraform validate
  - terraform apply -auto-approve
  - terraform destroy -auto-approve
