language: minimal

before_install:
- echo "before_install"

install:
- echo "install"

before_script:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - terraform -v
  
 script:
  - echo "script"
  
  
